### ISSUE TITLE
Ubuntu 18.04 5.4.5 mainline kernel asm_inline crashes build

### ISSUE THREAD

**Issue by 9Lukas5** [tomaspinho/rtl8821ce#112]
Hey,

I got the attached makelog, starting with the following:
```log
DKMS make.log for rtl8821ce-v5.5.2_34066.20190614 for kernel 5.4.5-050405-generic (x86_64)
Do 19. Dez 18:13:02 CET 2019
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.4.5-050405-generic/build M=/var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build  modules
make[1]: Verzeichnis „/usr/src/linux-headers-5.4.5-050405-generic“ wird betreten
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8821ce/v5.5.2_34066.20190614/build/core/rtw_io.o
In file included from <command-line>:0:0:
./arch/x86/include/asm/page_64.h: In function ‘clear_page’:
././include/linux/compiler_types.h:210:20: error: ‘asm_inline’ undeclared (first use in this function); did you mean ‘apm_info’?
 #define asm_inline asm_inline
```

I were able to compile the driver successfully after editing the kernel header in the named file `compiler_types.h` to define the same in the upper if block as in the else block:
```h
#ifdef CONFIG_CC_HAS_ASM_INLINE
#define asm_inline asm __inline
#else
#define asm_inline asm
#endif
```

Is this a bug of ubuntu or for this driver?

L

[make.log](https://github.com/tomaspinho/rtl8821ce/files/3984788/make.log)

**Comment by tomaspinho** [comment]
Honestly, this looks like a Ubuntu bug on that mainline version, because I've just been able to compile this on Manjaro with kernel `5.4.6`. I was able to reproduce your problem in a Ubuntu docker container, however.

**Comment by Syniurge** [comment]
I had the same error.

Ubuntu 18.04 comes with GCC 7.4, and `asm __inline` was introduced in GCC 7.5:
https://github.com/torvalds/linux/commit/eb111869301e15b737315a46c913ae82bd19eb9d

Kernels from https://kernel.ubuntu.com/~kernel-ppa/mainline/ are built with a newer GCC:
```bash
$ cat /proc/version 
Linux version 5.4.7-050407-generic (kernel@gloin) (gcc version 9.2.1 20191130 (Ubuntu 9.2.1-21ubuntu1)) #201912311234 SMP Tue Dec 31 17:38:50 UTC 2019
```

It's definitely not this driver's fault, because simply including one kernel header making use of `asm_inline` triggers the error. It ignores the mismatching GCC versions, and I think that's for the better since ABI breakage with C code doesn't happen every day.

Another workaround without altering the kernel header is to install GCC 8.3:
```bash
apt install gcc-8
```
and add this line at the top of rtl8821ce/Makefile:
```make
CC = gcc-8
```
Re-install the DKMS module (with `dkms-remove.sh` then `dkms-install.sh`) and it should build with GCC 8.3.

The workaround is Ubuntu 18.04-specific (there's no GCC 9 in the official packages), so I don't know what a proper workaround/fix that works for everyone would be.

**Comment by tomaspinho** [comment]
@Syniurge thanks for the workaround! :)
