### ISSUE TITLE
new fedora update breaks the drivers

### ISSUE THREAD

**Issue by H3n-beep** [tomaspinho/rtl8821ce#248]
i was using fedora ws35 just fine but with the new update not only i cant connect to internet anymore (no adaptor found) nor i can re install the driver and had to roll back to previous version
EDIT: the new commit solved the issue thanks

**Comment by frankcrawford** [comment]
If you are talking about the latest kernel update for Fedora, it is because they have moved to kernel version 5.15.4, and as noted, rtl8821ce currently have issues with 5.15 and later.
Note, the latest commit attempts to fix this issue, so try pulling the latest version of the driver from here and try running that.I haven't yet upgraded, and so haven't tested to see if it corrects the issue, but will do so in the next few days.

**Comment by jesseruu** [comment]
I upgraded to 5.15 and yeah it breaks the driver so I tried to update the driver since I was quite behind and I saw the new commit that fix the issue but I noticed that is not even necessary to use this driver anymore at least for me. I removed the driver to make the upgrade then I rebooted the system and everything works fine without the driver.

I would recommend to remove the driver and check if everything works. If that's not the case then pull the latest version and try that.

**Comment by frankcrawford** [comment]
Yes, there is now an official driver in the kernel tree which works for some models of the card.  If it works fine for you, it is simpler to use it.

**Comment by GunpowderGuy** [comment]
Unfortunately some wifi cards still dont work well with the official driver. Mine causes my laptop to crash intermittently

**Comment by H3n-beep** [comment]
the new commit indeed solved the issue for my wifi connection on fedora ws 35 thanks
