### ISSUE TITLE
When I go to use Bluetooth with WiFi, It's not working!

### ISSUE THREAD

**Issue by sakibulalikhan** [tomaspinho/rtl8821ce#287]
When I go to use **Bluetooth** _with_ **WiFi** on my laptop, the **internet** becomes **_very slow_** so nothing can be done with the internet. _But if I only use WiFi then it works properly_. It just made a problem when I try to use the booth at one time. Hopefully, I'll get it resolved quickly.

**Comment by dubhater** [comment]
No one is developing this driver. You would have a better chance with the built-in rtw88 driver. That one has problems too, but at least the Realtek developers are still maintaining it. If you report a bug in rtw88, they may fix it.

**Comment by sakibulalikhan** [comment]
Hey, is this the driver's repo?
https://github.com/lwfinger/rtw88

And am I reporting the same thing on this repo's issue?

**Comment by dubhater** [comment]
First of all, you have to check if you have the same problem with rtw88. It's a completely different driver.

rtw88 is integrated in the kernel and it supports RTL8821CE since version 5.9 or so. Larry Finger's repo has the same code you can find in the latest kernel, but with fixes to allow compilation for older kernels. If your kernel is older than 5.18, I recommend blacklisting rtw88_8821ce (the integrated version) and using Larry Finger's repo. That way you won't encounter any bugs that were already fixed.

If the computer freezes when you use rtw88, you can put these lines in /etc/modprobe.d/rtw88.conf:
```
options rtw88_pci disable_aspm=1 # integrated driver
options rtw_pci disable_aspm=1 # Larry Finger's version
```
Then you have to shut down the computer. Rebooting is not enough in this case. The freezing is supposed to be fixed already, but maybe not for everyone.

When you switch to rtw88, blacklist the ``8821ce`` module, or remove it completely. You should also shut down instead of rebooting when you switch to rtw88, or back to 8821ce.

If rtw88 is not working correctly, you should send an email to the ``linux-wireless [at] vger.kernel.org`` mailing list (you don't have to subscribe first). Make sure the subject line starts with "rtw88" so the maintainer sees your email. For example, "rtw88: Using Bluetooth makes Wifi slow", or "rtw88: It makes the computer freeze".

You can also open an issue in Larry Finger's repo, but he only fixes compilation errors.
