### ISSUE TITLE
Make AUR package dependency 'linux-headers' optional

### ISSUE THREAD

**Issue by WAlbeda** [tomaspinho/rtl8821ce#302]
Please make the linux-headers dependency for the AUR package optional like [this comment](https://aur.archlinux.org/packages/rtl8821ce-dkms-git#comment-879507) explains, so people who want to use other kernel packages like 'lts' or 'zen' don't need to keep the linux-headers package installed on their systems.

**Comment by UnkwUsr** [comment]
You can manually replace `linux-headers` with `linux-zen-headers` in your own `PKGBUILD` (as I personally did in my case) and then run `makepkg -si`. And then you don't need `linux-headers` package.

I think total removing `linux-headers` will confuse some newbies (with weird error on package installing step), because you actually must have `*-headers` package for the kernel you use.

P.S. I'm not an expert in `PKGBUILD` files or kernel stuff.

**Comment by WAlbeda** [comment]
I understand that I could manually replace the dependencies in the pkgbuild but like most other users probably do, I use a package manager for easily updating all my AUR packages (yay in my case) and it'll save me (and probably all the other non-vanilla kernel users) a lot of frustration of every time this package updates editing the dependencies.
For the newbies I think it will not be a big issue because as a newbie running Arch you will probably need to read the arch wiki about installing AUR packages anyways and since the wiki hammers a lot on reading the pkgbuild before installing you will probably have read the optional dependencies (and hopefully the github readme wich also tells you need a *-headers package).

**Comment by tomaspinho** [comment]
Done!
